### PR TITLE
fix bug with PID UI values not being set properly.

### LINKED ISSUE #52: Fix PID issues
it takes way too long to slow down/stop

### PR DESCRIPTION
**Pull request by cdj5492**
Fix #52

### CODE REVIEW

File: core_pb/src/driving/motors.rs [hunk 1]
```diff
@@ -153,6 +159,13 @@ pub async fn motors_task<T: RobotMotorsBehavior>(
         {
             last_command = T::Instant::default();
             data.config = msg;
+            // for mut controller in data.pid_controllers {
```
Comment (MJE10) [inline core_pb/src/driving/motors.rs]: pls remove

File: core_pb/src/driving/motors.rs [hunk 2]
```diff
@@ -114,11 +116,15 @@ pub async fn motors_task<T: RobotMotorsBehavior>(
                     // calculate pid
                     data.pid_controllers[m].setpoint(data.set_points[m]);
                     let output = data.pid_controllers[m].next_control_output(measured_speeds[m]);
-                    let output = output.output;
-                    if output > 0.0 {
-                        data.pwm[m] = [output.abs().round() as u16, 0];
+                    let output_built = output.output + data.prev_out[m];
+                    data.prev_out[m] = output_built;
+                    println!("motor {:?} output_built={:?}, input={:?}, speed={:?}", m, output_built, data.set_points[m], measured_speeds[m]);
```
Comment (MJE10) [inline core_pb/src/driving/motors.rs]: pls change to debug!, should be able to import from use crate::driving::debug because it has a cfg to swap between std and nostd environments

**Review by MJE10 — CHANGES_REQUESTED** [review]

File: core_pb/src/driving/motors.rs (hunk 2 above)
Comment (MJE10) [reply core_pb/src/driving/motors.rs]: was removed before I posted this

Comment (cdj5492) [reply core_pb/src/driving/motors.rs]: I'll just get rid of it. Not relevant anymore

**Review by MJE10 — APPROVED** [review]
lgtm if build passes
